import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import {Flex} from "antd";
import React from "react";
import Header from "@/components/Header";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
									   children,
								   }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body className={inter.className + "body"}>
			<Flex style={{display: "flex", justifyContent: "center"}} gap="middle">
				<SideBar/>
				<div style={{maxWidth: "1200px", width: "100%"}}>
					{children}
				</div>
			</Flex>
		</body>
		</html>
	);
}
